config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  resources :categories, only: [:index, :show, :new, :create] do
    resources :trades, only: [:new, :create]
  end

end

app/models/Category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  has_and_belongs_to_many :trades
  belongs_to :user
end

app/models/Entity.rb
class Entity < ApplicationRecord
  validates :name, presence: true
  validates :amount, numbericality: { greater_than_or_equal_to(0) }

  has_and_belongs_to_many :groups
  belongs_to :user
end

app/models/Group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  has_and_belongs_to_many :entities
  belongs_to :user
end

app/models/Trade.rb
class Trade < ApplicationRecord
  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  has_and_belongs_to_many :categories
  belongs_to :author, class_name: 'User'
end

app/models/User.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :name, presence: true
  has_many :categories
  has_many :trades, foreign_key: 'author_id', class_name: 'Trade', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true

  has_and_belongs_to_many :trades
  belongs_to :user
end

app/models/trade.rb
class Trade < ApplicationRecord
  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }

  has_and_belongs_to_many :categories
  belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :categories
  has_many :trades, foreign_key: 'author_id', class_name: 'Trade', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  helper CategoriesHelper

  def index
    if current_user
      @categories = Category.includes(:trades).where(user: current_user)
    else
      redirect root_path
    end
  end

  def show
    if current_user
      @category = Category.find(params[:id])
      trades = @category.trades
      @trades = trades.sort_by { |t| -t.created_at.to_i }
    else
      redirect_to categories_path
    end
  end

  def new; end

  def create
    category = Category.new(category_params)
    category.user = current_user
    category.trades = []
    if category.save
      flash[:notice] = 'New category was created successfully'
      redirect_to categories_path
    else
      flash[:alert] = 'Error! Category could not create'
      redirect_to new_category_path
    end
  end

  private

  def category_params
    params.required(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.find(params[:category_id])
  end

  def create
    trade = Trade.new(name: trade_params[:name], amount: trade_params[:amount])
    trade.author = current_user
    trade.categories << Category.find(trade_params[:category])
    if trade.save
      flash[:notice] = 'New trade was created successfully'
      redirect_to categories_path
    else
      flash[:alert] = 'Error! Could not create new trade'
      redirect_to new_trade_path
    end
  end

  private

  def trade_params
    params.required(:trade).permit(:name, :amount, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/categories/index.html.erb
<%= javascript_importmap_tags %>
<%= yield(:head)%>
<% content_for :head do %>
  <%= javascript_import_module_tag "index" %>
<% end %>

<div class="h-full flex flex-col justify-between">
  <section class="bg-[#3778c2] text-white p-2">
    <div class="flex justify-between mb-3 items-center">
      <div class="relative menu" id="menu">
        <button class="w-5 h-5 cursor-pointer" type="button" >
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
        <nav id="nav" class="hidden absolute top-5">
          <ul>
            <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure'} %></li>
          </ul>
        </nav>
      </div>

      <h2>CATEGORIES</h2>
      <span class="w-5 h-5">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>
      </span>
    </div>
  </section>
  <%= render partial: 'shared/flash' %>

  <section class="h-full bg-gray-200 flex flex-col space-y-2 pt-2 items-center">
    <% @categories&.map do |category| %>
      <div class="flex justify-between p-2 shadow-md bg-white gap-2 w-[95%] rounded-sm">
        <div class="flex justify-between gap-2">
          <%= image_tag category.icon, class: 'w-14 h-14' %>
          <div class="flex flex-col justify-between">
            <p class="pt-1"><%= link_to category.name, category_path(category) %></p>
            <p class="text-xs"><%= category.created_at %></p>
          </div>
        </div>
        <p class="mr-2">
        $<%= category.trades.reduce(0) { |sum, tr| sum + tr.amount } %>
        </p>
      </div>
    <% end %>
  </section>

  <section class="bg-[#5fb523] text-white py-2 text-center flex">
    <%= link_to 'ADD CATEGORIES', new_category_path, class: 'border border-solid border-white mx-2 py-2 w-full hover:text-amber-300' %>
  </section>

</div>

app/views/categories/new.html.erb
<div class="h-full flex flex-col">
  <%= render partial: 'shared/header_bar', locals: { url: categories_path, title: 'NEW CATEGORY' }%>

  <%= form_with model: Category.new, url: categories_path, method: :post, local: true, html: { class: 'flex flex-col justify-between h-full'} do |f| %>
    <div>
      <%= f.text_field :name, placeholder: 'Name', class: 'w-full p-2' %>
      <%= f.text_field :icon, placeholder: 'Icon Url', class: 'w-full p-2'  %>
    </div>
    <div class="bg-[#5fb523] text-white py-2 text-center flex">
      <%= f.submit 'SAVE' , class: 'border border-solid border-white mx-2 py-2 w-full hover:text-amber-300'%>
    </div>
  <% end %>

</div>

app/views/categories/show.html.erb
<div class="flex flex-col h-full">
  <%= render partial: 'shared/header_bar', locals: { title: 'TRADES', url: '/' } %>
  <div class="flex justify-end pb-2 px-2 text-xs space-x-2 bg-[#3778c2]">
      <p class="text-white">Most recent</p>
  </div>

  <div class="flex h-full flex-col items-center justify-between p-2 shadow-md bg-white gap-2 w-full rounded-sm">
    <div class="flex justify-between w-[95%] items-center">
      <div class="flex justify-between gap-2 items-center">
        <%= image_tag @category.icon, class: 'w-14 h-14' %>
        <p class="pt-1"><%= link_to @category.name, category_path(@category) %></p>
      </div>
      <p class="mr-2">
        $<%= @category.trades.reduce(0) { |sum, tr| sum + tr.amount } %>
      </p>
    </div>
    <div class="h-full flex flex-col p-2 w-full">
      <% @trades&.each do |t| %>
        <div class="shadow-lg flex justify-between py-4 px-3 w-full items-center">
          <p><%= t.name %></p>
          <p>$<%= t.amount %></p>
        </div>
      <% end %>
    </div>

  </div>
    <section class="bg-[#5fb523] text-white py-2 text-center flex">
      <%= link_to 'ADD TRADE', new_category_trade_path(@category), class: 'border border-solid border-white mx-2 py-2 w-full hover:text-amber-300' %>
    </section>
</div>

app/views/home/index.html.erb
<div class="h-full flex flex-col justify-end items-center">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Lobster+Two:wght@700&display=swap');

    .logo {
      font-family: 'Lobster Two', cursive;
      font-size: 40px;
      font-weight: 700;
    }
  </style>
  <span class="flex justify-center items-center h-full">
    <h1 class="text-cyan-400 logo">Budget App</h1>
  </span>
  <div class="w-full flex flex-col justify-center items-center gap-2">
    <span class="w-full">
      <%= button_to 'LOG IN', new_user_session_path, class: 'w-full text-white bg-[#3778c2] py-2 rounded hover:bg-opacity-80' %>
    </span>
    <span class="w-full group/edit">
      <%= button_to 'SIGN UP', new_user_registration_path, method: :get, class: 'border rounded w-full py-2 group-hover/edit:translate-x-0.5 group-hover/edit:bg-slate-200' %>
    </span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", async: true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <div class="flex justify-center items-center bg-[#3778c2] h-screen">
      <div class="w-80 h-[600px] border rounded-lg shadow-2xl bg-zinc-500 px-2 py-4">
        <div class="border rounded-lg h-full overflow-auto px-1 py-3 bg-white">
          <%= yield %>
        </div>
      </>
    </div>
  </body>
</html>

app/views/shared/_button.html.erb
<section class="bg-[#5fb523] text-white py-2 text-center flex">
    <%= button_to title, url, class: 'border border-solid border-white mx-2 py-2 w-full hover:text-amber-300' %>
</section>

app/views/shared/_flash.html.erb
<% if notice || alert %>
  <div class="h-10">
    <p class="notice text-green-400"><%= notice %></p>
    <p class="alert text-red-500"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_header_bar.html.erb
<div class="bg-[#3778c2] text-white flex justify-between p-2 items-center w-full">
    <span class="w-5 h-5">
      <%= link_to(url) do %>
      <svg fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75"></path>
      </svg>
      <% end %>
    </span>
    <h2 class="font-weight-bold"><%= title %></h2>
    <span class="w-3"></span>
</div>

app/views/trades/new.html.erb
<div class="h-full flex flex-col">
  <%= render partial: 'shared/header_bar', locals: { url: categories_path, title: 'NEW TRADE' }%>

  <%= form_with model: Trade.new, url: category_trades_path(@category), method: :post, local: true, html: { class: 'flex flex-col justify-between items-center h-full space-y-3 bg-gray-200'} do |f| %>
    <div class="flex flex-col w-[95%] items-center gap-2">
      <%= f.text_field :name, placeholder: 'Name', class: 'w-full p-2 space-y-2' %>
      <%= f.number_field :amount, step: 0.01, placeholder: 'Amount', class: 'w-full p-2'  %>
      <%= f.collection_select :category, Category.where(user: current_user), :id, :name, {prompt: 'Select a category'}, class: 'w-full p-2' %>
    </div>
    <div class="bg-[#5fb523] text-white py-2 text-center flex w-full">
      <%= f.submit 'SAVE' , class: 'border border-solid border-white mx-2 py-2 w-full hover:text-amber-300'%>
    </div>
  <% end %>

</div>